CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    PARENT_ID NUMBER,
    CONSTRAINT FK_CATEGORY_PARENT
        FOREIGN KEY (PARENT_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(100,'커피',NULL);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(101,'아메리카노류',100);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(102,'라떼류',100);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(103,'디카페인',100);

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(200,'논커피',NULL);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(201,'논커피 라떼',200);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(202,'주스류',200);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES(203,'티',200);

CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR2(4) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_EXPLAIN VARCHAR2(200),
    PRODUCT_PRICE NUMBER NOT NULL,
    PRODUCT_STOCK NUMBER,
    CATEGORY_ID NUMBER,
    CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
        );
INSERT INTO PRODUCTS VALUES('C001','아메리카노','에스프레소 샷, 물',2000,200,101);
INSERT INTO PRODUCTS VALUES('L001','카페라떼','에스프레소 샷, 우유',2900,100,102);
INSERT INTO PRODUCTS VALUES('L002','카페모카','에스프레소 샷, 초코 시럽, 우유',3500,100,102);
INSERT INTO PRODUCTS VALUES('D001','디카페인 아메리카노','디카페인 샷, 물',3000,100,103);

INSERT INTO PRODUCTS VALUES('N001','딸기라떼','딸기청, 우유',3500,50,201);
INSERT INTO PRODUCTS VALUES('N002','녹차라떼','녹차베이스, 우유',3500,50,201);
INSERT INTO PRODUCTS VALUES('J001','청포도 주스','청포도, 물, 시럽',3800,30,202);
INSERT INTO PRODUCTS VALUES('T001','캐모마일',NULL,3000,50,203);

CREATE TABLE USERS (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_PHONE VARCHAR2(15) NOT NULL,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_ROLE NUMBER NOT NULL);
    
INSERT INTO USERS VALUES('SJ001','곽소정','Ksj0828','010-1234-5678','siena08@naver.com',2);
INSERT INTO USERS VALUES('EY001','양은영','Yang1234','010-4567-7891','yang12@naver.com',1);
INSERT INTO USERS VALUES('KL001','강이도은','Kang1234','010-1234-5555','kang12@naver.com',1);
INSERT INTO USERS VALUES('YR001','양록빈','Rock1234','010-4654-4564','rock12@naver.com',1);
INSERT INTO USERS VALUES('NH001','노현주','Noh1234','010-4455-1122','noh12@naver.com',1);

CREATE TABLE C_ORDER (
    ORDER_ID VARCHAR2(4) PRIMARY KEY,
    PRODUCT_ID VARCHAR2(4) NOT NULL,
    ORDER_STOCK NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_C_ORDERS_PRODUCTS
        FOREIGN KEY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),
        
    CONSTRAINT FK_C_ORDERS_USERS
        FOREIGN KEY(USER_ID)
        REFERENCES USERS(USER_ID)
        );

CREATE TABLE CART (
    USER_ID VARCHAR2(20) NOT NULL,
    PRODUCT_ID VARCHAR2(4) NOT NULL,
      CONSTRAINT FK_C_CART_PRODUCTS
        FOREIGN KEY(PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID),
        
    CONSTRAINT FK_C_CART_USERS
        FOREIGN KEY(USER_ID)
        REFERENCES USERS(USER_ID)
        );
    
COMMIT;
